AllCops:
  TargetRubyVersion: 2.4
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Layout/AlignHash:
  EnforcedHashRocketStyle: separator
  EnforcedColonStyle: separator
Style/FrozenStringLiteralComment:
  Enabled: false
